services:
  db:
    image: postgres
    restart: always

    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=idontknow
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: